[font]
normal = { family = "Iosevka Term",  style = "Regular"}
# normal = { family = "JetBrainsMono Nerd Font",  style = "Regular"}
size = 24

[window]
option_as_alt = "Both"
# opacity = 0.82

[general]
import = [
  # "~/.config/alacritty/theme.toml"
  "~/.config/alacritty/jellybeans.toml"
]
