theme = "tokyonight_storm"

[editor]
line-number = "relative"
color-modes = true
true-color = true
bufferline = "always"
# bufferline = "multiple"
# bufferline = "never"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
