theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
true-color = true
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
