---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  terminal_font_size: 16
  theme: catppuccin-mocha
  # image_protocol: kitty-local

typst:
  ppi: 300

export:
  pdf:
    fonts:
      normal: /Users/mkurzynski/Library/Fonts/MonaspaceArgonFrozen-Regular.ttf
      italic: /Users/mkurzynski/Library/Fonts/MonaspaceArgonFrozen-Italic.ttf
      bold: /Users/mkurzynski/Library/Fonts/MonaspaceArgonFrozen-Bold.ttf
      bold_italic: /Users/mkurzynski/Library/Fonts/MonaspaceArgonFrozen-BoldItalic.ttf
